### PR TITLE
Make dumpinfo parsing also strong clean

### PR DESCRIPTION
**Pull request by sigmundch**

### CODE REVIEW

**Comment by sigmundch** [comment]
@efortuna

**Comment by sigmundch** [comment]
@kevmoo - how does one turn on --preview-dart-2 on vm tests in travis?

**Comment by harryterkelsen** [comment]
I forgot to check this, but you should also bump the version number so you can pull this into the SDK

**Comment by sigmundch** [comment]
Thanks - actually, I included this with 0.5.6+4 (it wasn't published yet). I tagged the release on this commit though.

**Comment by kevmoo** [comment]
Enable on travis (for the VM, pub run, etc):
https://github.com/dart-lang/build/pull/1474/files#diff-b1de5166a13e970c48aaa8bfb6775ef8

**Comment by kevmoo** [comment]
...you can also set the `env` variable in .travis.yml

https://docs.travis-ci.com/user/environment-variables/#Defining-public-variables-in-.travis.yml

**Pull request merged**
